FROM continuumio/miniconda3:4.8.2

# FROM python:3.9.7

LABEL software.version="0.0.0"
LABEL image.name="linfengwang/tb-ml-drug-resistance-prediction-from-one-hot-encoded-consensus-sequence"

ADD main.py .

RUN conda install -c conda-forge\
    pandas\
    numpy \
    pytorch \
    torchvision \
    scikit-learn \
    argparse

    # pytorch=1.12.1 \
    # torchvision=0.13.1 \
    # sklearn=1.0.2 \
    # argparse=1.1

# # create a directory for the internal data used by the container
# USER root
# RUN mkdir /internal_data /data

# copy the python main and bash entrypoint scripts

# set `/data` as working directory so that the output is written to the
# mount point when run with `docker run -v $PWD:/data ... -o output.csv`
# WORKDIR /data

CMD ["python", "main.py"]
